### ISSUE TITLE
Append configs to machine.config without replacing entire file. 

### ISSUE THREAD

**Issue by simeononsecurity** [simeononsecurity/.NET-STIG-Script#1]
```
<enforceFIPSPolicy enabled="true"/>
<loadFromRemoteSources enabled="false" "*" />
<NetFx40_LegacySecurityPolicy enabled="true"/>
<etwEnable enabled="true"/>
```

and 
```
   <system.net>
        <defaultProxy>
        </defaultProxy>
        <connectionManagement>
            <add address="*" maxconnection="24" />
        </connectionManagement>
    </system.net>
```

**Comment by simeononsecurity** [comment]
Attempted to set up something using .NET calls. But I couldn't get it working. 
I'd like to merge the file at https://github.com/simeononsecurity/.NET-STIG-Script/blob/master/Files/machine.config
With the local systems Machine.conf. 
Any help here would be appreciated. I've tried like 15 different ways. 
```ps
[xml]$SecureMachineConfig = Get-Content $currentPath\Files\machine.config
Apply Machine.conf Configurations
Foreach ($netframework in $netframeworks){
    Write-Host $netframework
    ForEach ($machineconfig in (Get-ChildItem -Recurse -Path $netframework machine.config).FullName){
        Write-Host "$machineconfig"
        ForEach ($node in ($SecureMachineConfig.DocumentElement.ChildNodes)){
        [xml]$defaultmachineconfig=(Get-Content $machineconfig)
        $defaultmachineconfig.ImportNode($node, $true) 
        Write-Host "Murge Complete"
        }
    }
}
```

**Comment by authantik** [comment]
> ```
> <enforceFIPSPolicy enabled="true"/>
> <loadFromRemoteSources enabled="false" "*" />
> <NetFx40_LegacySecurityPolicy enabled="true"/>
> <etwEnable enabled="true"/>
> ```
> 
> and 
> ```
>    <system.net>
>         <defaultProxy>
>         <connectionManagement>
>             <add address="*" maxconnection="24" />
>         </connectionManagement>
>     </system.net>
> ```

**Comment by simeononsecurity** [comment]
> > ```
> > <enforceFIPSPolicy enabled="true"/>
> > <loadFromRemoteSources enabled="false" "*" />
> > <NetFx40_LegacySecurityPolicy enabled="true"/>
> > <etwEnable enabled="true"/>
> > ```
> > 
> > 
> > and
> > ```
> >    <system.net>
> >         <defaultProxy>
> >         <connectionManagement>
> >             <add address="*" maxconnection="24" />
> >         </connectionManagement>
> >     </system.net>
> > ```

?

**Comment by simeononsecurity** [comment]
Saw the following [here](https://stackoverflow.com/questions/39925805/writing-to-the-machine-config-file-in-powershell):
```powershell

$numberOfCores = Get-WmiObject -class win32_processor numberOfCores | Select-Object -ExpandProperty numberOfCores

$machineConfig = [System.Configuration.ConfigurationManager]::OpenMachineConfiguration()

$processModel = $machineConfig.SectionGroups['system.web'].ProcessModel
$processModel.SectionInformation.RevertToParent()
$processModel.MaxWorkerThreads = 370
$processModel.MaxIOThreads = 370
$processModel.MinWorkerThreads = 50
$processModel.MinIOThreads = 50

$httpRuntime = $machineConfig.SectionGroups['system.web'].HttpRuntime
$httpRuntime.MinFreeThreads = 90 * $numberOfCores
$httpRuntime.MinLocalRequestFreeThreads = 80 * $numberOfCores

$connectionManagement = $machineConfig.SectionGroups['system.net'].ConnectionManagement
$connectionManagement.ConnectionManagement.Add((New-Object System.Net.Configuration.ConnectionManagementElement *, (200 * $numberOfCores)))

$machineConfig.Save()
```
Possible way of implementing the required changes?
