### ISSUE TITLE
Windows Update requiring .NET Framework 3.5 broken

### ISSUE THREAD

**Issue by olsonperrensen** [simeononsecurity/.NET-STIG-Script#3]
**Describe the bug**
Update fails due to error code 0x800f081f. This seems to be tied with .NET 3.5 and below. When trying to turn feature on you get a Group Policy error.

**To Reproduce**
1. Go to Windows Update
2. Click on 2024-01 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5034123)
3. See update failure
4. Try to solve error by enabling .NET Framework 3.5
5. See error saying Group Policy prevents this from happening

**Expected behavior**
Having the option to temporarily re-enable .NET Framework 3.5 

**Screenshots**
![OptionalFeatures_Rp5h1aOHEA](https://github.com/simeononsecurity/.NET-STIG-Script/assets/80784184/907f0270-a0fe-4324-a81a-ffc94a3a6eff)
![ApplicationFrameHost_426YBIHE4g](https://github.com/simeononsecurity/.NET-STIG-Script/assets/80784184/8f911bb7-0c13-4f1b-80b2-0d273906e2b7)
![OptionalFeatures_mCOkAdTsWx](https://github.com/simeononsecurity/.NET-STIG-Script/assets/80784184/dcc0eca0-7bb1-4f7c-b94f-8d8aa8c4be88)

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22631.2428
 - Version 22631.2428

**Additional context**
-

**Comment by simeononsecurity** [comment]
Thanks @olsonperrensen for the great issue submission!

It doesn't surprise us that something would eventually break from this. Microsoft/Windows doesn't even implement support for the hardening best practices correctly in most of their applications. 

Our best suggestion for you in the mean time, is to revert to a restore point or snapshot, or reinstall windows. 

Prior to running this script again, please remove or rename the files in the files folder to prevent some of the more game breaking bugs. You'll see that we've already done that in our other repos that take advantage of this script. 
That should fix any .net issues you're having. 

Alternatively, you can try using the offline standalone installer for .net 3.5

https://dotnet.microsoft.com/en-us/download/dotnet-framework/net35-sp1
